package org.codenarc.idea;

import org.jetbrains.annotations.NotNull;

import com.intellij.codeInspection.LocalQuickFix;
import org.codenarc.rule.Rule;
import org.codenarc.rule.Violation;

import org.codenarc.rule.basic.*;
import org.codenarc.rule.braces.*;
import org.codenarc.rule.comments.*;
import org.codenarc.rule.concurrency.*;
import org.codenarc.rule.convention.*;
import org.codenarc.rule.design.*;
import org.codenarc.rule.dry.*;
import org.codenarc.rule.exceptions.*;
import org.codenarc.rule.formatting.*;
import org.codenarc.rule.generic.*;
import org.codenarc.rule.grails.*;
import org.codenarc.rule.groovyism.*;
import org.codenarc.rule.imports.*;
import org.codenarc.rule.jdbc.*;
import org.codenarc.rule.junit.*;
import org.codenarc.rule.logging.*;
import org.codenarc.rule.naming.*;
import org.codenarc.rule.security.*;
import org.codenarc.rule.serialization.*;
import org.codenarc.rule.size.*;
import org.codenarc.rule.unnecessary.*;
import org.codenarc.rule.unused.*;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public final class CodeNarcQuickFixMappings {

    private static final Map<Class<? extends Rule>, LocalQuickFix[]> mappings;

    static {
        Map<Class<? extends Rule>, LocalQuickFix[]> map = new HashMap<Class<? extends Rule>, LocalQuickFix[]>();

        map.put(AbcMetricRule.class, new LocalQuickFix[]{});   // Requires the GMetrics jar
        map.put(AbstractClassNameRule.class, new LocalQuickFix[]{});
        map.put(AbstractClassWithPublicConstructorRule.class, new LocalQuickFix[]{});
        map.put(AbstractClassWithoutAbstractMethodRule.class, new LocalQuickFix[]{});
        map.put(AddEmptyStringRule.class, new LocalQuickFix[]{});
        map.put(AssertWithinFinallyBlockRule.class, new LocalQuickFix[]{});
        map.put(AssignCollectionSortRule.class, new LocalQuickFix[]{});
        map.put(AssignCollectionUniqueRule.class, new LocalQuickFix[]{});
        map.put(AssignmentInConditionalRule.class, new LocalQuickFix[]{});
        map.put(AssignmentToStaticFieldFromInstanceMethodRule.class, new LocalQuickFix[]{});
        map.put(BigDecimalInstantiationRule.class, new LocalQuickFix[]{});
        map.put(BitwiseOperatorInConditionalRule.class, new LocalQuickFix[]{});
        map.put(BlankLineBeforePackageRule.class, new LocalQuickFix[]{});
        map.put(BlockEndsWithBlankLineRule.class, new LocalQuickFix[]{});
        map.put(BlockStartsWithBlankLineRule.class, new LocalQuickFix[]{});
        map.put(BooleanGetBooleanRule.class, new LocalQuickFix[]{});
        map.put(BooleanMethodReturnsNullRule.class, new LocalQuickFix[]{});
        map.put(BracesForClassRule.class, new LocalQuickFix[]{});
        map.put(BracesForForLoopRule.class, new LocalQuickFix[]{});
        map.put(BracesForIfElseRule.class, new LocalQuickFix[]{});
        map.put(BracesForMethodRule.class, new LocalQuickFix[]{});
        map.put(BracesForTryCatchFinallyRule.class, new LocalQuickFix[]{});
        map.put(BrokenNullCheckRule.class, new LocalQuickFix[]{});
        map.put(BrokenOddnessCheckRule.class, new LocalQuickFix[]{});
        map.put(BuilderMethodWithSideEffectsRule.class, new LocalQuickFix[]{});
        map.put(BusyWaitRule.class, new LocalQuickFix[]{});
        map.put(CatchArrayIndexOutOfBoundsExceptionRule.class, new LocalQuickFix[]{});
        map.put(CatchErrorRule.class, new LocalQuickFix[]{});
        map.put(CatchExceptionRule.class, new LocalQuickFix[]{});
        map.put(CatchIllegalMonitorStateExceptionRule.class, new LocalQuickFix[]{});
        map.put(CatchIndexOutOfBoundsExceptionRule.class, new LocalQuickFix[]{});
        map.put(CatchNullPointerExceptionRule.class, new LocalQuickFix[]{});
        map.put(CatchRuntimeExceptionRule.class, new LocalQuickFix[]{});
        map.put(CatchThrowableRule.class, new LocalQuickFix[]{});
        map.put(ChainedTestRule.class, new LocalQuickFix[]{});
        map.put(ClassEndsWithBlankLineRule.class, new LocalQuickFix[]{});
        map.put(ClassForNameRule.class, new LocalQuickFix[]{});
        map.put(ClassJavadocRule.class, new LocalQuickFix[]{});
        map.put(ClassNameRule.class, new LocalQuickFix[]{});
        map.put(ClassNameSameAsFilenameRule.class, new LocalQuickFix[]{});
        map.put(ClassNameSameAsSuperclassRule.class, new LocalQuickFix[]{});
        map.put(ClassSizeRule.class, new LocalQuickFix[]{});
        map.put(ClassStartsWithBlankLineRule.class, new LocalQuickFix[]{});
        map.put(CloneWithoutCloneableRule.class, new LocalQuickFix[]{});
        map.put(CloneableWithoutCloneRule.class, new LocalQuickFix[]{});
        map.put(CloseWithoutCloseableRule.class, new LocalQuickFix[]{});
        map.put(ClosureAsLastMethodParameterRule.class, new LocalQuickFix[]{});
        map.put(ClosureStatementOnOpeningLineOfMultipleLineClosureRule.class, new LocalQuickFix[]{});
        map.put(CollectAllIsDeprecatedRule.class, new LocalQuickFix[]{});
        map.put(CompareToWithoutComparableRule.class, new LocalQuickFix[]{});
        map.put(ComparisonOfTwoConstantsRule.class, new LocalQuickFix[]{});
        map.put(ComparisonWithSelfRule.class, new LocalQuickFix[]{});
        map.put(ConfusingClassNamedExceptionRule.class, new LocalQuickFix[]{});
        map.put(ConfusingMethodNameRule.class, new LocalQuickFix[]{});
        map.put(ConfusingMultipleReturnsRule.class, new LocalQuickFix[]{});
        map.put(ConfusingTernaryRule.class, new LocalQuickFix[]{});
        map.put(ConsecutiveBlankLinesRule.class, new LocalQuickFix[]{});
        map.put(ConsecutiveLiteralAppendsRule.class, new LocalQuickFix[]{});
        map.put(ConsecutiveStringConcatenationRule.class, new LocalQuickFix[]{});
        map.put(ConstantAssertExpressionRule.class, new LocalQuickFix[]{});
        map.put(ConstantIfExpressionRule.class, new LocalQuickFix[]{});
        map.put(ConstantTernaryExpressionRule.class, new LocalQuickFix[]{});
        map.put(ConstantsOnlyInterfaceRule.class, new LocalQuickFix[]{});
        map.put(CouldBeElvisRule.class, new LocalQuickFix[]{});
        map.put(CouldBeSwitchStatementRule.class, new LocalQuickFix[]{});
        map.put(CoupledTestCaseRule.class, new LocalQuickFix[]{});
        map.put(CrapMetricRule.class, new LocalQuickFix[]{});   // Requires the GMetrics jar and a Cobertura coverage file
        map.put(CyclomaticComplexityRule.class, new LocalQuickFix[]{});   // Requires the GMetrics jar
        map.put(DeadCodeRule.class, new LocalQuickFix[]{});
        map.put(DirectConnectionManagementRule.class, new LocalQuickFix[]{});
        map.put(DoubleCheckedLockingRule.class, new LocalQuickFix[]{});
        map.put(DoubleNegativeRule.class, new LocalQuickFix[]{});
        map.put(DuplicateCaseStatementRule.class, new LocalQuickFix[]{});
        map.put(DuplicateImportRule.class, new LocalQuickFix[]{});
        map.put(DuplicateListLiteralRule.class, new LocalQuickFix[]{});
        map.put(DuplicateMapKeyRule.class, new LocalQuickFix[]{});
        map.put(DuplicateMapLiteralRule.class, new LocalQuickFix[]{});
        map.put(DuplicateNumberLiteralRule.class, new LocalQuickFix[]{});
        map.put(DuplicateSetValueRule.class, new LocalQuickFix[]{});
        map.put(DuplicateStringLiteralRule.class, new LocalQuickFix[]{});
        map.put(ElseBlockBracesRule.class, new LocalQuickFix[]{});
        map.put(EmptyCatchBlockRule.class, new LocalQuickFix[]{});
        map.put(EmptyClassRule.class, new LocalQuickFix[]{});
        map.put(EmptyElseBlockRule.class, new LocalQuickFix[]{});
        map.put(EmptyFinallyBlockRule.class, new LocalQuickFix[]{});
        map.put(EmptyForStatementRule.class, new LocalQuickFix[]{});
        map.put(EmptyIfStatementRule.class, new LocalQuickFix[]{});
        map.put(EmptyInstanceInitializerRule.class, new LocalQuickFix[]{});
        map.put(EmptyMethodRule.class, new LocalQuickFix[]{});
        map.put(EmptyMethodInAbstractClassRule.class, new LocalQuickFix[]{});
        map.put(EmptyStaticInitializerRule.class, new LocalQuickFix[]{});
        map.put(EmptySwitchStatementRule.class, new LocalQuickFix[]{});
        map.put(EmptySynchronizedStatementRule.class, new LocalQuickFix[]{});
        map.put(EmptyTryBlockRule.class, new LocalQuickFix[]{});
        map.put(EmptyWhileStatementRule.class, new LocalQuickFix[]{});
        map.put(EnumCustomSerializationIgnoredRule.class, new LocalQuickFix[]{});
        map.put(EqualsAndHashCodeRule.class, new LocalQuickFix[]{});
        map.put(EqualsOverloadedRule.class, new LocalQuickFix[]{});
        map.put(ExceptionExtendsErrorRule.class, new LocalQuickFix[]{});
        map.put(ExceptionExtendsThrowableRule.class, new LocalQuickFix[]{});
        map.put(ExceptionNotThrownRule.class, new LocalQuickFix[]{});
        map.put(ExplicitArrayListInstantiationRule.class, new LocalQuickFix[]{});
        map.put(ExplicitCallToAndMethodRule.class, new LocalQuickFix[]{});
        map.put(ExplicitCallToCompareToMethodRule.class, new LocalQuickFix[]{});
        map.put(ExplicitCallToDivMethodRule.class, new LocalQuickFix[]{});
        map.put(ExplicitCallToEqualsMethodRule.class, new LocalQuickFix[]{});
        map.put(ExplicitCallToGetAtMethodRule.class, new LocalQuickFix[]{});
        map.put(ExplicitCallToLeftShiftMethodRule.class, new LocalQuickFix[]{});
        map.put(ExplicitCallToMinusMethodRule.class, new LocalQuickFix[]{});
        map.put(ExplicitCallToModMethodRule.class, new LocalQuickFix[]{});
        map.put(ExplicitCallToMultiplyMethodRule.class, new LocalQuickFix[]{});
        map.put(ExplicitCallToOrMethodRule.class, new LocalQuickFix[]{});
        map.put(ExplicitCallToPlusMethodRule.class, new LocalQuickFix[]{});
        map.put(ExplicitCallToPowerMethodRule.class, new LocalQuickFix[]{});
        map.put(ExplicitCallToPutAtMethodRule.class, new LocalQuickFix[]{});
        map.put(ExplicitCallToRightShiftMethodRule.class, new LocalQuickFix[]{});
        map.put(ExplicitCallToXorMethodRule.class, new LocalQuickFix[]{});
        map.put(ExplicitGarbageCollectionRule.class, new LocalQuickFix[]{});
        map.put(ExplicitHashMapInstantiationRule.class, new LocalQuickFix[]{});
        map.put(ExplicitHashSetInstantiationRule.class, new LocalQuickFix[]{});
        map.put(ExplicitLinkedHashMapInstantiationRule.class, new LocalQuickFix[]{});
        map.put(ExplicitLinkedListInstantiationRule.class, new LocalQuickFix[]{});
        map.put(ExplicitStackInstantiationRule.class, new LocalQuickFix[]{});
        map.put(ExplicitTreeSetInstantiationRule.class, new LocalQuickFix[]{});
        map.put(FactoryMethodNameRule.class, new LocalQuickFix[]{});
        map.put(FieldNameRule.class, new LocalQuickFix[]{});
        map.put(FieldTypeRequiredRule.class, new LocalQuickFix[]{});
        map.put(FileCreateTempFileRule.class, new LocalQuickFix[]{});
        map.put(FileEndsWithoutNewlineRule.class, new LocalQuickFix[]{});
        map.put(FinalClassWithProtectedMemberRule.class, new LocalQuickFix[]{});
        map.put(ForLoopShouldBeWhileLoopRule.class, new LocalQuickFix[]{});
        map.put(ForStatementBracesRule.class, new LocalQuickFix[]{});
        map.put(GStringAsMapKeyRule.class, new LocalQuickFix[]{});
        map.put(GStringExpressionWithinStringRule.class, new LocalQuickFix[]{});
        map.put(GetterMethodCouldBePropertyRule.class, new LocalQuickFix[]{});
        map.put(GrailsDomainHasEqualsRule.class, new LocalQuickFix[]{});
        map.put(GrailsDomainHasToStringRule.class, new LocalQuickFix[]{});
        map.put(GrailsDomainReservedSqlKeywordNameRule.class, new LocalQuickFix[]{});
        map.put(GrailsDomainStringPropertyMaxSizeRule.class, new LocalQuickFix[]{});
        map.put(GrailsDomainWithServiceReferenceRule.class, new LocalQuickFix[]{});
        map.put(GrailsDuplicateConstraintRule.class, new LocalQuickFix[]{});
        map.put(GrailsDuplicateMappingRule.class, new LocalQuickFix[]{});
        map.put(GrailsMassAssignmentRule.class, new LocalQuickFix[]{});
        map.put(GrailsPublicControllerMethodRule.class, new LocalQuickFix[]{});
        map.put(GrailsServletContextReferenceRule.class, new LocalQuickFix[]{});
        map.put(GrailsStatelessServiceRule.class, new LocalQuickFix[]{});
        map.put(GroovyLangImmutableRule.class, new LocalQuickFix[]{});
        map.put(HardCodedWindowsFileSeparatorRule.class, new LocalQuickFix[]{});
        map.put(HardCodedWindowsRootDirectoryRule.class, new LocalQuickFix[]{});
        map.put(HashtableIsObsoleteRule.class, new LocalQuickFix[]{});
        map.put(IfStatementBracesRule.class, new LocalQuickFix[]{});
        map.put(IfStatementCouldBeTernaryRule.class, new LocalQuickFix[]{});
        map.put(IllegalClassMemberRule.class, new LocalQuickFix[]{});
        map.put(IllegalClassReferenceRule.class, new LocalQuickFix[]{});
        map.put(IllegalPackageReferenceRule.class, new LocalQuickFix[]{});
        map.put(IllegalRegexRule.class, new LocalQuickFix[]{});
        map.put(IllegalStringRule.class, new LocalQuickFix[]{});
        map.put(IllegalSubclassRule.class, new LocalQuickFix[]{});
        map.put(ImplementationAsTypeRule.class, new LocalQuickFix[]{});
        map.put(ImportFromSamePackageRule.class, new LocalQuickFix[]{});
        map.put(ImportFromSunPackagesRule.class, new LocalQuickFix[]{});
        map.put(InconsistentPropertyLockingRule.class, new LocalQuickFix[]{});
        map.put(InconsistentPropertySynchronizationRule.class, new LocalQuickFix[]{});
        map.put(IndentationRule.class, new LocalQuickFix[]{});
        map.put(InsecureRandomRule.class, new LocalQuickFix[]{});
        map.put(InstanceofRule.class, new LocalQuickFix[]{});
        map.put(IntegerGetIntegerRule.class, new LocalQuickFix[]{});
        map.put(InterfaceNameRule.class, new LocalQuickFix[]{});
        map.put(InterfaceNameSameAsSuperInterfaceRule.class, new LocalQuickFix[]{});
        map.put(InvertedConditionRule.class, new LocalQuickFix[]{});
        map.put(InvertedIfElseRule.class, new LocalQuickFix[]{});
        map.put(JUnitAssertAlwaysFailsRule.class, new LocalQuickFix[]{});
        map.put(JUnitAssertAlwaysSucceedsRule.class, new LocalQuickFix[]{});
        map.put(JUnitAssertEqualsConstantActualValueRule.class, new LocalQuickFix[]{});
        map.put(JUnitFailWithoutMessageRule.class, new LocalQuickFix[]{});
        map.put(JUnitLostTestRule.class, new LocalQuickFix[]{});
        map.put(JUnitPublicFieldRule.class, new LocalQuickFix[]{});
        map.put(JUnitPublicNonTestMethodRule.class, new LocalQuickFix[]{});
        map.put(JUnitPublicPropertyRule.class, new LocalQuickFix[]{});
        map.put(JUnitSetUpCallsSuperRule.class, new LocalQuickFix[]{});
        map.put(JUnitStyleAssertionsRule.class, new LocalQuickFix[]{});
        map.put(JUnitTearDownCallsSuperRule.class, new LocalQuickFix[]{});
        map.put(JUnitTestMethodWithoutAssertRule.class, new LocalQuickFix[]{});
        map.put(JUnitUnnecessarySetUpRule.class, new LocalQuickFix[]{});
        map.put(JUnitUnnecessaryTearDownRule.class, new LocalQuickFix[]{});
        map.put(JUnitUnnecessaryThrowsExceptionRule.class, new LocalQuickFix[]{});
        map.put(JavaIoPackageAccessRule.class, new LocalQuickFix[]{});
        map.put(JavadocConsecutiveEmptyLinesRule.class, new LocalQuickFix[]{});
        map.put(JavadocEmptyAuthorTagRule.class, new LocalQuickFix[]{});
        map.put(JavadocEmptyExceptionTagRule.class, new LocalQuickFix[]{});
        map.put(JavadocEmptyFirstLineRule.class, new LocalQuickFix[]{});
        map.put(JavadocEmptyLastLineRule.class, new LocalQuickFix[]{});
        map.put(JavadocEmptyParamTagRule.class, new LocalQuickFix[]{});
        map.put(JavadocEmptyReturnTagRule.class, new LocalQuickFix[]{});
        map.put(JavadocEmptySeeTagRule.class, new LocalQuickFix[]{});
        map.put(JavadocEmptySinceTagRule.class, new LocalQuickFix[]{});
        map.put(JavadocEmptyThrowsTagRule.class, new LocalQuickFix[]{});
        map.put(JavadocEmptyVersionTagRule.class, new LocalQuickFix[]{});
        map.put(JdbcConnectionReferenceRule.class, new LocalQuickFix[]{});
        map.put(JdbcResultSetReferenceRule.class, new LocalQuickFix[]{});
        map.put(JdbcStatementReferenceRule.class, new LocalQuickFix[]{});
        map.put(LineLengthRule.class, new LocalQuickFix[]{});
        map.put(LocaleSetDefaultRule.class, new LocalQuickFix[]{});
        map.put(LoggerForDifferentClassRule.class, new LocalQuickFix[]{});
        map.put(LoggerWithWrongModifiersRule.class, new LocalQuickFix[]{});
        map.put(LoggingSwallowsStacktraceRule.class, new LocalQuickFix[]{});
        map.put(LongLiteralWithLowerCaseLRule.class, new LocalQuickFix[]{});
        map.put(MethodCountRule.class, new LocalQuickFix[]{});
        map.put(MethodNameRule.class, new LocalQuickFix[]{});
        map.put(MethodParameterTypeRequired.class, new LocalQuickFix[]{});
        map.put(MethodReturnTypeRequiredRule.class, new LocalQuickFix[]{});
        map.put(MethodSizeRule.class, new LocalQuickFix[]{});
        map.put(MisorderedStaticImportsRule.class, new LocalQuickFix[]{});
        map.put(MissingBlankLineAfterImportsRule.class, new LocalQuickFix[]{});
        map.put(MissingBlankLineAfterPackageRule.class, new LocalQuickFix[]{});
        map.put(MissingNewInThrowStatementRule.class, new LocalQuickFix[]{});
        map.put(MultipleLoggersRule.class, new LocalQuickFix[]{});
        map.put(MultipleUnaryOperatorsRule.class, new LocalQuickFix[]{});
        map.put(NestedBlockDepthRule.class, new LocalQuickFix[]{});
        map.put(NestedForLoopRule.class, new LocalQuickFix[]{});
        map.put(NestedSynchronizationRule.class, new LocalQuickFix[]{});
        map.put(NoDefRule.class, new LocalQuickFix[]{});
        map.put(NoJavaUtilDateRule.class, new LocalQuickFix[]{});
        map.put(NoTabCharacterRule.class, new LocalQuickFix[]{});
        map.put(NoWildcardImportsRule.class, new LocalQuickFix[]{});
        map.put(NonFinalPublicFieldRule.class, new LocalQuickFix[]{});
        map.put(NonFinalSubclassOfSensitiveInterfaceRule.class, new LocalQuickFix[]{});
        map.put(ObjectFinalizeRule.class, new LocalQuickFix[]{});
        map.put(ObjectOverrideMisspelledMethodNameRule.class, new LocalQuickFix[]{});
        map.put(PackageNameRule.class, new LocalQuickFix[]{});
        map.put(PackageNameMatchesFilePathRule.class, new LocalQuickFix[]{});
        map.put(ParameterCountRule.class, new LocalQuickFix[]{});
        map.put(ParameterNameRule.class, new LocalQuickFix[]{});
        map.put(ParameterReassignmentRule.class, new LocalQuickFix[]{});
        map.put(PrintStackTraceRule.class, new LocalQuickFix[]{});
        map.put(PrintlnRule.class, new LocalQuickFix[]{});
        map.put(PrivateFieldCouldBeFinalRule.class, new LocalQuickFix[]{});
        map.put(PropertyNameRule.class, new LocalQuickFix[]{});
        map.put(PublicFinalizeMethodRule.class, new LocalQuickFix[]{});
        map.put(PublicInstanceFieldRule.class, new LocalQuickFix[]{});
        map.put(PublicMethodsBeforeNonPublicMethodsRule.class, new LocalQuickFix[]{});
        map.put(RandomDoubleCoercedToZeroRule.class, new LocalQuickFix[]{});
        map.put(RemoveAllOnSelfRule.class, new LocalQuickFix[]{});
        map.put(RequiredRegexRule.class, new LocalQuickFix[]{});
        map.put(RequiredStringRule.class, new LocalQuickFix[]{});
        map.put(ReturnFromFinallyBlockRule.class, new LocalQuickFix[]{});
        map.put(ReturnNullFromCatchBlockRule.class, new LocalQuickFix[]{});
        map.put(ReturnsNullInsteadOfEmptyArrayRule.class, new LocalQuickFix[]{});
        map.put(ReturnsNullInsteadOfEmptyCollectionRule.class, new LocalQuickFix[]{});
        map.put(SerialPersistentFieldsRule.class, new LocalQuickFix[]{});
        map.put(SerialVersionUIDRule.class, new LocalQuickFix[]{});
        map.put(SerializableClassMustDefineSerialVersionUIDRule.class, new LocalQuickFix[]{});
        map.put(SimpleDateFormatMissingLocaleRule.class, new LocalQuickFix[]{});
        map.put(SpaceAfterCatchRule.class, new LocalQuickFix[]{});
        map.put(SpaceAfterClosingBraceRule.class, new LocalQuickFix[]{});
        map.put(SpaceAfterCommaRule.class, new LocalQuickFix[]{});
        map.put(SpaceAfterForRule.class, new LocalQuickFix[]{});
        map.put(SpaceAfterIfRule.class, new LocalQuickFix[]{});
        map.put(SpaceAfterOpeningBraceRule.class, new LocalQuickFix[]{});
        map.put(SpaceAfterSemicolonRule.class, new LocalQuickFix[]{});
        map.put(SpaceAfterSwitchRule.class, new LocalQuickFix[]{});
        map.put(SpaceAfterWhileRule.class, new LocalQuickFix[]{});
        map.put(SpaceAroundClosureArrowRule.class, new LocalQuickFix[]{});
        map.put(SpaceAroundMapEntryColonRule.class, new LocalQuickFix[]{});
        map.put(SpaceAroundOperatorRule.class, new LocalQuickFix[]{});
        map.put(SpaceBeforeClosingBraceRule.class, new LocalQuickFix[]{});
        map.put(SpaceBeforeOpeningBraceRule.class, new LocalQuickFix[]{});
        map.put(SpockIgnoreRestUsedRule.class, new LocalQuickFix[]{});
        map.put(StatelessClassRule.class, new LocalQuickFix[]{});
        map.put(StatelessSingletonRule.class, new LocalQuickFix[]{});
        map.put(StaticCalendarFieldRule.class, new LocalQuickFix[]{});
        map.put(StaticConnectionRule.class, new LocalQuickFix[]{});
        map.put(StaticDateFormatFieldRule.class, new LocalQuickFix[]{});
        map.put(StaticFieldsBeforeInstanceFieldsRule.class, new LocalQuickFix[]{});
        map.put(StaticMatcherFieldRule.class, new LocalQuickFix[]{});
        map.put(StaticMethodsBeforeInstanceMethodsRule.class, new LocalQuickFix[]{});
        map.put(StaticSimpleDateFormatFieldRule.class, new LocalQuickFix[]{});
        map.put(SwallowThreadDeathRule.class, new LocalQuickFix[]{});
        map.put(SynchronizedMethodRule.class, new LocalQuickFix[]{});
        map.put(SynchronizedOnBoxedPrimitiveRule.class, new LocalQuickFix[]{});
        map.put(SynchronizedOnGetClassRule.class, new LocalQuickFix[]{});
        map.put(SynchronizedOnReentrantLockRule.class, new LocalQuickFix[]{});
        map.put(SynchronizedOnStringRule.class, new LocalQuickFix[]{});
        map.put(SynchronizedOnThisRule.class, new LocalQuickFix[]{});
        map.put(SynchronizedReadObjectMethodRule.class, new LocalQuickFix[]{});
        map.put(SystemErrPrintRule.class, new LocalQuickFix[]{});
        map.put(SystemExitRule.class, new LocalQuickFix[]{});
        map.put(SystemOutPrintRule.class, new LocalQuickFix[]{});
        map.put(SystemRunFinalizersOnExitRule.class, new LocalQuickFix[]{});
        map.put(TernaryCouldBeElvisRule.class, new LocalQuickFix[]{});
        map.put(ThisReferenceEscapesConstructorRule.class, new LocalQuickFix[]{});
        map.put(ThreadGroupRule.class, new LocalQuickFix[]{});
        map.put(ThreadLocalNotStaticFinalRule.class, new LocalQuickFix[]{});
        map.put(ThreadYieldRule.class, new LocalQuickFix[]{});
        map.put(ThrowErrorRule.class, new LocalQuickFix[]{});
        map.put(ThrowExceptionRule.class, new LocalQuickFix[]{});
        map.put(ThrowExceptionFromFinallyBlockRule.class, new LocalQuickFix[]{});
        map.put(ThrowNullPointerExceptionRule.class, new LocalQuickFix[]{});
        map.put(ThrowRuntimeExceptionRule.class, new LocalQuickFix[]{});
        map.put(ThrowThrowableRule.class, new LocalQuickFix[]{});
        map.put(ToStringReturnsNullRule.class, new LocalQuickFix[]{});
        map.put(TrailingCommaRule.class, new LocalQuickFix[]{});
        map.put(TrailingWhitespaceRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryBigDecimalInstantiationRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryBigIntegerInstantiationRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryBooleanExpressionRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryBooleanInstantiationRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryCallForLastElementRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryCallToSubstringRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryCastRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryCatchBlockRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryCollectCallRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryCollectionCallRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryConstructorRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryDefInFieldDeclarationRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryDefInMethodDeclarationRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryDefInVariableDeclarationRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryDotClassRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryDoubleInstantiationRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryElseStatementRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryFailRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryFinalOnPrivateMethodRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryFloatInstantiationRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryGStringRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryGetterRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryGroovyImportRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryIfStatementRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryInstanceOfCheckRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryInstantiationToGetClassRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryIntegerInstantiationRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryLongInstantiationRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryModOneRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryNullCheckRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryNullCheckBeforeInstanceOfRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryObjectReferencesRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryOverridingMethodRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryPackageReferenceRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryParenthesesForMethodCallWithClosureRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryPublicModifierRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryReturnKeywordRule.class, new LocalQuickFix[]{});
        map.put(UnnecessarySafeNavigationOperatorRule.class, new LocalQuickFix[]{});
        map.put(UnnecessarySelfAssignmentRule.class, new LocalQuickFix[]{});
        map.put(UnnecessarySemicolonRule.class, new LocalQuickFix[]{});
        map.put(UnnecessarySetterRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryStringInstantiationRule.class, new LocalQuickFix[]{});
        map.put(UnnecessarySubstringRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryTernaryExpressionRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryToStringRule.class, new LocalQuickFix[]{});
        map.put(UnnecessaryTransientModifierRule.class, new LocalQuickFix[]{});
        map.put(UnsafeArrayDeclarationRule.class, new LocalQuickFix[]{});
        map.put(UnsafeImplementationAsMapRule.class, new LocalQuickFix[]{});
        map.put(UnusedArrayRule.class, new LocalQuickFix[]{});
        map.put(UnusedImportRule.class, new LocalQuickFix[]{});
        map.put(UnusedMethodParameterRule.class, new LocalQuickFix[]{});
        map.put(UnusedObjectRule.class, new LocalQuickFix[]{});
        map.put(UnusedPrivateFieldRule.class, new LocalQuickFix[]{});
        map.put(UnusedPrivateMethodRule.class, new LocalQuickFix[]{});
        map.put(UnusedPrivateMethodParameterRule.class, new LocalQuickFix[]{});
        map.put(UnusedVariableRule.class, new LocalQuickFix[]{});
        map.put(UseAssertEqualsInsteadOfAssertTrueRule.class, new LocalQuickFix[]{});
        map.put(UseAssertFalseInsteadOfNegationRule.class, new LocalQuickFix[]{});
        map.put(UseAssertNullInsteadOfAssertEqualsRule.class, new LocalQuickFix[]{});
        map.put(UseAssertSameInsteadOfAssertTrueRule.class, new LocalQuickFix[]{});
        map.put(UseAssertTrueInsteadOfAssertEqualsRule.class, new LocalQuickFix[]{});
        map.put(UseAssertTrueInsteadOfNegationRule.class, new LocalQuickFix[]{});
        map.put(UseCollectManyRule.class, new LocalQuickFix[]{});
        map.put(UseCollectNestedRule.class, new LocalQuickFix[]{});
        map.put(UseOfNotifyMethodRule.class, new LocalQuickFix[]{});
        map.put(VariableNameRule.class, new LocalQuickFix[]{});
        map.put(VariableTypeRequiredRule.class, new LocalQuickFix[]{});
        map.put(VectorIsObsoleteRule.class, new LocalQuickFix[]{});
        map.put(VolatileArrayFieldRule.class, new LocalQuickFix[]{});
        map.put(VolatileLongOrDoubleFieldRule.class, new LocalQuickFix[]{});
        map.put(WaitOutsideOfWhileLoopRule.class, new LocalQuickFix[]{});
        map.put(WhileStatementBracesRule.class, new LocalQuickFix[]{});

        mappings = Collections.unmodifiableMap(map);
    }

    public static @NotNull LocalQuickFix[] getQuickFixesFor(@NotNull Violation violation) {
        return mappings.get(violation.getRule().getClass());
    }
}
