/*
 *
 *
 *   Copyright 2011 C�dric Champeau
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 *  /
 * /
 */

package org.codenarc.idea;

import com.intellij.codeInspection.InspectionToolProvider;
import com.intellij.openapi.components.ApplicationComponent;
import org.jetbrains.annotations.NotNull;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.LinkedList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;


/**
 * Created by IntelliJ IDEA.
 * User: cedric
 * Date: 20/01/11
 * Time: 23:24
 */

/**
 * This component is responsible for loading the rules from the classpath, and "converting" them into IntelliJ IDEA
 * inspections. This is done by dynamically generating subclasses of {@link CodeNarcInspectionTool} class.
 *
 * @author Cédric Champeau
 */
public class CodeNarcComponent implements ApplicationComponent, InspectionToolProvider {

    protected static final String BASE_MESSAGES_BUNDLE = "codenarc-base-messages";

    private InspectionsClassLoader inspectionsClassLoader;
    private Class[] ruleInspectionClasses;

    private final static String[] rulesets = {
            "basic",
            "braces",
            "concurrency",
            "design",
            "dry",
            "exceptions",
            "generic",
            "grails",
            "imports",
            "junit",
            "logging",
            "naming",
            "size",
            "unnecessary",
            "unused"
    };
    private final static Pattern RULE_CLASS_PATTERN = Pattern.compile(".*class='(.*?)'.*");

    public void initComponent() {
        inspectionsClassLoader = new InspectionsClassLoader();
        initializeRuleInspectionClasses();
    }

    public void disposeComponent() {
        ruleInspectionClasses = null;
        inspectionsClassLoader = null;
    }

    @NotNull
    public String getComponentName() {
        return "CodeNarcComponent";
    }

    public Class[] getInspectionClasses() {
        return ruleInspectionClasses;
    }

    private void initializeRuleInspectionClasses() {
        List<Class> proxyclasses = new LinkedList<Class>();
        for (String ruleset : rulesets) {
            BufferedReader reader = new BufferedReader(new InputStreamReader(this.getClass().getResourceAsStream("/rulesets/" + ruleset + ".xml")));
            String line;
            try {
                while ((line = reader.readLine()) != null) {
                    Matcher m = RULE_CLASS_PATTERN.matcher(line);
                    if (m.find()) {
                        try {
                            final Class<?> ruleClass = Class.forName(m.group(1));
                            Class clazz = inspectionsClassLoader.defineClass(new ImplementGetRuleClassGenerator(ruleClass).toByteArray());
                            // initialize rule
                            proxyclasses.add(clazz);
                        } catch (ClassNotFoundException e) {
                            e.printStackTrace();
                        }
                    }
                }
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                if (reader != null) try {
                    reader.close();
                } catch (IOException e) {
                    // silent
                }
            }
        }

        ruleInspectionClasses = proxyclasses.toArray(new Class[proxyclasses.size()]);
    }

    /**
     * A classloader which allows us to load the byte[] generated by ASM.
     */
    static final class InspectionsClassLoader extends URLClassLoader {

        public InspectionsClassLoader() {
            super(new URL[0], CodeNarcComponent.class.getClassLoader());
        }

        protected Class defineClass(byte[] data) {
            return super.defineClass(null, data, 0, data.length);
        }
    }

    /**
     * A class generator which creates an implementation class for {@link CodeNarcInspectionTool}
     */
    private static class ImplementGetRuleClassGenerator implements Opcodes {
        private Class ruleClass;

        public ImplementGetRuleClassGenerator(Class ruleClass) {
            this.ruleClass = ruleClass;
        }

        public byte[] toByteArray() {
            ClassWriter cw = new ClassWriter(0);
            MethodVisitor mv;

            cw.visit(V1_6, ACC_PUBLIC + ACC_SUPER, "org/codenarc/idea/CodeNarcInpectionTool$" + ruleClass.getSimpleName(), null, "org/codenarc/idea/CodeNarcInspectionTool", null);

            {
                mv = cw.visitMethod(ACC_PUBLIC, "<init>", "()V", null, null);
                mv.visitCode();
                mv.visitVarInsn(ALOAD, 0);
                mv.visitMethodInsn(INVOKESPECIAL, "org/codenarc/idea/CodeNarcInspectionTool", "<init>", "()V");
                mv.visitInsn(RETURN);
                mv.visitMaxs(1, 1);
                mv.visitEnd();
            }
            {
                mv = cw.visitMethod(ACC_PROTECTED, "getRuleClass", "()Ljava/lang/Class;", null, null);
                mv.visitCode();
                mv.visitLdcInsn(Type.getType(ruleClass));
                mv.visitInsn(Opcodes.ARETURN);
                mv.visitMaxs(1, 1);
                mv.visitEnd();
            }
            cw.visitEnd();

            return cw.toByteArray();
        }

    }
}
