on:
  schedule:
    - cron: '30 0 * * *'
jobs:
  update-bom:
    name: Updates Version and Opens PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch CodeNarc Maven descriptor
        run: curl https://repo1.maven.org/maven2/org/codenarc/CodeNarc/maven-metadata.xml -o /tmp/codenarc-maven-descriptor.xml
      - name: Extract the latest version
        uses: QwerMike/xpath-action@v1
        id: xpath
        with:
          filename: '/tmp/codenarc-maven-descriptor.xml'
          expression: '/metadata/versioning/latest/text()'
      - name: Upgrade CodenarcVersion Number
        run: |
          sed -i 's/codenarcVersion.*/codenarcVersion=${{ steps.xpath.outputs.result }}/' gradle.properties
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        name: Regenerate Inspection Tool Classes
        with:
          arguments: run --stacktrace
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Upgraded to CodeNarc ${{ steps.xpath.outputs.result }}
          title: '[Upgrade] Upgraded to the CodeNarc ${{ steps.xpath.outputs.result }}'
          body: |
            There is a newer version ${{ steps.xpath.outputs.result }} of CodeNarc available. The dependency has been updated and the inspection tools
            have been regenerated.
          labels: chore,upgrade
          assignees: musketyr
          branch: upgrade/codenarc
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
