name: Release to Prod Channel

on:
  release:
    types: [published]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Xmx6g -Xms4g"
    steps:
      - uses: actions/checkout@v3
      - name: Semantic Version
        id: version
        uses: ncipollo/semantic-version-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: publishPlugin -PpublishPluginToken=${{ secrets.JB_PLUGINS_TOKEN }} -PideVersion=IC-2023.1 -PgroovyVersion=4.0.10 -PspockVersion=2.3-groovy-4.0 -PpluginVersion=${{ steps.version.outputs.tag }}
